const ADD_GEOLOCATION = "ADD_GEOLOCATION";
const ADD_ITEMS = "ADD_ITEMS";
const CHANGE_ERROR = "CHANGE_ERROR";
const CHANGE_ERROR_MESSAGE = "CHANGE_ERROR_MESSAGE";
const CHANGE_CITIES = "CHANGE_CITIES";
const DELETE_CITY = "DELETE_CITY";
const CHANGE_CONNECTION = "CHANGE_CONNECTION";
const CHANGE_CITY_LOADING = "CHANGE_CITY_LOADING";

export {
    ADD_GEOLOCATION,
    ADD_ITEMS,
    CHANGE_ERROR,
    CHANGE_ERROR_MESSAGE,
    CHANGE_CITIES,
    DELETE_CITY,
    CHANGE_CONNECTION,
    CHANGE_CITY_LOADING,
}